require 'rgl/adjacency'
require 'rgl/base'
require 'rgl/bellman_ford'
require 'rgl/bidirectional'
require 'rgl/bipartite'
require 'rgl/condensation'
require 'rgl/connected_components'
require 'rgl/dijkstra'
require 'rgl/dijkstra_visitor'
require 'rgl/dot'
require 'rgl/edge_properties_map'
require 'rgl/edmonds_karp'
require 'rgl/graph_iterator'
require 'rgl/graph_visitor'
require 'rgl/graph_wrapper'
require 'rgl/graphxml'
require 'rgl/implicit'
require 'rgl/mutable'
require 'rgl/path_builder'
require 'rgl/prim'
require 'rgl/rdot'
require 'rgl/topsort'
require 'rgl/transitiv_closure'
require 'rgl/transitivity'
require 'rgl/traversal'

Containers::Graph = RGL::AdjacencyGraph
Containers::DirectedGraph = RGL::DirectedAdjacencyGraph
Containers::ImplicitGraph = RGL::ImplicitGraph